category_icons:
  type: string
  default: "1,heart|2,times"
  description: "Choose icons & topics order for corresponding category IDs. ex. '6,heart,title-asc' would assign the heart icon to category 6 & will order topic list by ascending activity. NOTE: order can be (title,activity)-(asc/desc)"
category_description:
  type: bool
  default: false
  description: "Enable the category description to be displayed in the category card filters for the docs page."
tag_icons:
  type: string
  default: "featured,heart|videos,times"
  description: "Choose icons & topics order for corresponding tag slugs. ex. 'featured,heart,activity-desc' would assign the heart icon to featured tag & will order topic list by ascending activity. NOTE: order can be (title,activity)-(asc/desc)"
custom_queries:
  type: list
  description: "Create custom queries to render cards for them"